### ISSUE TITLE
Test won't show in the report

### ISSUE THREAD

**Issue by trombomart** [rubenwiersma/thefirstorder#36]
The PDF export test isn't taken into account in the test report.

**Comment by hungnguyen94** [comment]
How did you initialize the PDF export class? It doesn't have a constructor.

**Comment by trombomart** [comment]
@hungnguyen94 you don't have to initialize the class. You use the export method as a static one.

**Comment by hungnguyen94** [comment]
It wasn't static before. But it is now.

**Comment by trombomart** [comment]
@hungnguyen94 So how do you make sure the test for the pdf export is taken into account?
