### ISSUE TITLE
Long method in timeline controller

### ISSUE THREAD

**Issue by rubenwiersma** [rubenwiersma/thefirstorder#38]
The controller method in the timeline is a bit too long. We've merged the code, but made this issue to make sure we don't forget.

**Comment by hungnguyen94** [comment]
See also #42

**Comment by hungnguyen94** [comment]
The Mapview code can be refactored to something much more simple. Just use use `vm.cameras = Camera.query();` instead of creating a function with an `onSucces` and `onError` function that does the same.

**Comment by cadw** [comment]
Does not work, have tried, is not global

**Comment by hungnguyen94** [comment]
Fixed in #65.
