### ISSUE TITLE
Confusing relations between entities

### ISSUE THREAD

**Issue by hungnguyen94** [rubenwiersma/thefirstorder#41]
Currently, the relations between entities are a bit confusing and all bi-directional. 
Maybe it's a better idea to make them uni-directional and make them more clear. For example, a Cue doesn't need to know which Script it belongs to. 
CameraAction could be changed to Action, so it's more flexible. It could also be changed so you don't need a new instance for every reference.

**Comment by trombomart** [comment]
I'm on it

**Comment by hungnguyen94** [comment]
#54 and #50
