### ISSUE TITLE
We should consider using a DTO to pass data to Angular. 

### ISSUE THREAD

**Issue by hungnguyen94** [rubenwiersma/thefirstorder#58]
In the Mapview, all required entities are queried one by one. Instead, we could just use a Data Transfer Object, to return all objects in a single call.

**Comment by rubenwiersma** [comment]
![hungcodeart](https://cloud.githubusercontent.com/assets/9115743/15608017/2eeadffc-2417-11e6-8b32-6b5ce2636949.jpg)

**Comment by hungnguyen94** [comment]
Implemented this in #65.
