### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ValMai** [rubenwiersma/thefirstorder#9]
Hi there,

I made a public repository where I will publish feedback every week. Each release on this repository is the feedback for each iteration. 
Here is the first release:
https://github.com/ValMai/cp2016-mm-feedback/releases/tag/iteration1
If you have any questions, don't hesitate to contact me on Slack. 

Regards,
Valentine

**Comment by rubenwiersma** [comment]
Thanks! We have incorporated the feedback on the sprint backlog in our latest version and will try to work it into the documents we'll be creating in the next couple of days.
